server:
 port:10000
 
h2:
 console:
  enabled: true

spring:
 sql:
  init:
   mode: always 
#앱 실행시 schema.sql 자동 실행
 datasource:
  url: jdbc:h2:mem:testdb
#H2 db용 JDBC 드라이버 클래스  
  driver: org.h2.Driver
#기본사용자  
  username: sa
#생략 가능(기본값 : 빈 문자열)
  password: 
  
mybatis:
#Mybatis 매퍼 XML 파일 위치
#스프링 부트에서는 resources 폴더가 자동으로 calsspath에 포함된다.
 mapper-locations: classpath:/mappers/**/*.xml
#DTO/VO 클래스 경로 설정
#XML에서 이 경로 내의 클래스들은 자동으로 별칭이 등록된다.
 type-aliases-package: com.korea.mybatis.domain
 configuration:
#db컬럼명과 자바 필드명 자동 매핑
#user_id => userId
  map-underscore-to-camel-case: true 
   
 	